version: '3.9'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: ["/entrypoint.sh"]
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  pgdata:
